### ISSUE TITLE
F1 Menu issue

### ISSUE THREAD

**Issue by Lt7S** [AStupidRat/RatPoison#17]
Everything In the hacks work except for the menu I have to manually edit configs to get what I want This is the error:
"****" is censored

`Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\****\AppData\Local\Temp\libgdx**** ??\135ea35f\lwjgl.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at org.lwjgl.system.Library$1.load(Library.java:25)
        at org.lwjgl.system.Library$1.load(Library.java:22)
        at org.lwjgl.system.Library.loadLibrary(Library.java:196)
        at org.lwjgl.system.Library.loadSystem(Library.java:90)
        at org.lwjgl.system.Library.<clinit>(Library.java:48)
        at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:56)
        at org.lwjgl.system.libffi.Closure.<clinit>(Closure.java:57)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:66)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:75)
        at rat.poison.RatPoison.main(RatPoison.kt:76)
        at rat.poison.RatPoison.main(RatPoison.kt)`

**Comment by AStupidRat** [comment]
@Lt7S When you run the .bat to start poison it should generate the files you need. You are using start rat poison version#.bat, not running it as admin, and are 64bit?

**Comment by Lt7S** [comment]
it generates all the files I tried as admin and Yes I am 64bit.

**Comment by Lt7S** [comment]
+ lastest version and java I have version 211 and tried installing 191 too

**Comment by AStupidRat** [comment]
https://drive.google.com/file/d/1BCG0toTY98ajIr0OiTClCSP3EYosUFnf/view Here are the files I have at that location

**Comment by Lt7S** [comment]
I have fixed the issue thanks

Can You add this to your hacks?  https://github.com/namazso/nSkinz

**Comment by AStupidRat** [comment]
I don't plan to add a skinchanger
