### ISSUE TITLE
GAME CRUSHES

### ISSUE THREAD

**Issue by thoma202411** [AStupidRat/RatPoison#19]
PLAYING IN CASUAL DIDNT DO ANYTHING. JUST WALKING AND THEN THE GAME CRUSHES AND LEAVE ME THE UI

kotlin.KotlinNullPointerException
        at rat.poison.game.WorldToScreenKt.worldToScreen(WorldToScreen.kt:14)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt:34)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt)
        at rat.poison.App.render(RatPoison.kt:210)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
        at rat.poison.RatPoison.main(RatPoison.kt:82)
kotlin.KotlinNullPointerException
        at rat.poison.game.WorldToScreenKt.worldToScreen(WorldToScreen.kt:14)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt:34)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt)
        at rat.poison.App.render(RatPoison.kt:210)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
        at rat.poison.RatPoison.main(RatPoison.kt:82)
kotlin.KotlinNullPointerException
        at rat.poison.game.WorldToScreenKt.worldToScreen(WorldToScreen.kt:14)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt:34)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt)
        at rat.poison.App.render(RatPoison.kt:210)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
        at rat.poison.RatPoison.main(RatPoison.kt:82)
kotlin.KotlinNullPointerException
        at rat.poison.game.WorldToScreenKt.worldToScreen(WorldToScreen.kt:14)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt:34)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt)
        at rat.poison.App.render(RatPoison.kt:210)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
        at rat.poison.RatPoison.main(RatPoison.kt:82)
kotlin.KotlinNullPointerException
        at rat.poison.game.WorldToScreenKt.worldToScreen(WorldToScreen.kt:14)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt:34)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt)
        at rat.poison.App.render(RatPoison.kt:210)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
        at rat.poison.RatPoison.main(RatPoison.kt:82)

![image](https://user-images.githubusercontent.com/41808115/57341172-295d0480-70ee-11e9-8afc-5ae299284673.png)

**Comment by AStupidRat** [comment]
Try with the updated version to begin with
