### ISSUE TITLE
While playing, got "Exception in thread "Thread-8"" error...

### ISSUE THREAD

**Issue by LauraSavall** [AStupidRat/RatPoison#28]
```
Exception in thread "Thread-8" javax.script.ScriptException: Error loading class Line_752: known classes: [Line_752, META-INF.kotlin-script.kotlin_module]
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:65)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:31)
        at javax.script.AbstractScriptEngine.eval(Unknown Source)
        at rat.poison.scripts.aim.SetAimKt$setAim$$inlined$every$1.invoke(Every.kt:27)
        at rat.poison.scripts.aim.SetAimKt$setAim$$inlined$every$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

Oh, and BTW, I'm borderless fullscreen, and UI is backgrounded... but, when I press F1, it come active...I need to alt tab to go back to CSGO

**Comment by AStupidRat** [comment]
Looks like you're running an older version, should be fine on the latest
