### ISSUE TITLE
Error In Built Project

### ISSUE THREAD

**Issue by RawTechnique** [AStupidRat/RatPoison#29]
Exception in thread "main" java.lang.NullPointerException
        at org.lwjgl.system.Checks.checkPointer(Checks.java:100)
        at org.lwjgl.glfw.GLFW.nglfwGetVideoMode(GLFW.java:993)
        at org.lwjgl.glfw.GLFW.glfwGetVideoMode(GLFW.java:1013)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:388)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:332)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:94)
        at rat.poison.RatPoison.main(RatPoison.kt:76)
        at rat.poison.RatPoison.main(RatPoison.kt)

**Comment by AStupidRat** [comment]
Does this error always happen or randomly and rarely? I believe I've had something similar and rerunning it fixed the problem.

**Comment by RawTechnique** [comment]
It always happens, and I cannot seem to find a fix.

**Comment by AStupidRat** [comment]
Let me know if the latest push fixes it

**Comment by RawTechnique** [comment]
Newest push results in the following 

Exception in thread "DefaultDispatcher-worker-2" java.lang.NullPointerException
        at org.lwjgl.system.Checks.checkPointer(Checks.java:100)
        at org.lwjgl.glfw.GLFW.nglfwGetVideoMode(GLFW.java:993)
        at org.lwjgl.glfw.GLFW.glfwGetVideoMode(GLFW.java:1013)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:388)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:332)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:94)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:85)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by 10urshin** [comment]
reinstall your graphics driver. DDU if persist. http://forum.lwjgl.org/index.php?PHPSESSID=qvesed72fdqfuok6svh04gc5q6&topic=5888.0

**Comment by RawTechnique** [comment]
@10urshin will do thanks!
