### ISSUE TITLE
OVER LAY UI ISSUE WITH ERROR CODE

### ISSUE THREAD

**Issue by thoma202411** [AStupidRat/RatPoison#38]
WHEN I CONSOLE QUIT THE CSGO THE OVERLAY UI IS STILL ON THE BACKGROUND 
AND THE ERROR CODES SHOWED ON THE TERMINAL IS 

kotlin.KotlinNullPointerException
        at rat.poison.game.WorldToScreenKt.worldToScreen(WorldToScreen.kt:14)
        at rat.poison.scripts.esp.IndicatorESPKt.w2sHandler(IndicatorESP.kt:121)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt:33)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt)
        at rat.poison.App.render(RatPoison.kt:218)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
![image](https://user-images.githubusercontent.com/41808115/57816301-a5c79700-772f-11e9-9329-27806dde5fb0.png)

**Comment by AStupidRat** [comment]
Overlay is supposed to stay open unless specifically closed. I'm not concerned with the error since if it loses csgo you should restart it anyways.
