### ISSUE TITLE
GAME CRUSHED

### ISSUE THREAD

**Issue by thoma202411** [AStupidRat/RatPoison#42]
WAS SHOOTING USING AWP THEN THE GAME SUDDENLY CRUSHED LEAVING THE UI BEHIND
ERROR CODE:kotlin.KotlinNullPointerException
        at rat.poison.game.WorldToScreenKt.worldToScreen(WorldToScreen.kt:14)
        at rat.poison.scripts.esp.IndicatorESPKt.w2sHandler(IndicatorESP.kt:121)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt:47)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt)
        at rat.poison.App.render(RatPoison.kt:217)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
kotlin.KotlinNullPointerException
        at rat.poison.game.WorldToScreenKt.worldToScreen(WorldToScreen.kt:14)
        at rat.poison.scripts.esp.IndicatorESPKt.w2sHandler(IndicatorESP.kt:121)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt:47)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt)
        at rat.poison.App.render(RatPoison.kt:217)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
kotlin.KotlinNullPointerException
        at rat.poison.game.WorldToScreenKt.worldToScreen(WorldToScreen.kt:14)
        at rat.poison.scripts.esp.IndicatorESPKt.w2sHandler(IndicatorESP.kt:121)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt:33)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt)
        at rat.poison.App.render(RatPoison.kt:217)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
kotlin.KotlinNullPointerException
        at rat.poison.game.WorldToScreenKt.worldToScreen(WorldToScreen.kt:14)
        at rat.poison.scripts.esp.IndicatorESPKt.w2sHandler(IndicatorESP.kt:121)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt:33)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt)
        at rat.poison.App.render(RatPoison.kt:217)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
kotlin.KotlinNullPointerException
        at rat.poison.game.WorldToScreenKt.worldToScreen(WorldToScreen.kt:14)
        at rat.poison.scripts.esp.IndicatorESPKt.w2sHandler(IndicatorESP.kt:121)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt:47)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt)
        at rat.poison.App.render(RatPoison.kt:217)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
kotlin.KotlinNullPointerException
        at rat.poison.game.WorldToScreenKt.worldToScreen(WorldToScreen.kt:14)
        at rat.poison.scripts.esp.IndicatorESPKt.w2sHandler(IndicatorESP.kt:121)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt:47)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt)
        at rat.poison.App.render(RatPoison.kt:217)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
kotlin.KotlinNullPointerException
        at rat.poison.game.WorldToScreenKt.worldToScreen(WorldToScreen.kt:14)
        at rat.poison.scripts.esp.IndicatorESPKt.w2sHandler(IndicatorESP.kt:121)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt:47)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt)
        at rat.poison.App.render(RatPoison.kt:217)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
kotlin.KotlinNullPointerException
        at rat.poison.game.WorldToScreenKt.worldToScreen(WorldToScreen.kt:14)
        at rat.poison.scripts.esp.IndicatorESPKt.w2sHandler(IndicatorESP.kt:121)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt:47)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt)
        at rat.poison.App.render(RatPoison.kt:217)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
kotlin.KotlinNullPointerException
        at rat.poison.game.WorldToScreenKt.worldToScreen(WorldToScreen.kt:14)
        at rat.poison.scripts.esp.IndicatorESPKt.w2sHandler(IndicatorESP.kt:121)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt:47)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt)
        at rat.poison.App.render(RatPoison.kt:217)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
kotlin.KotlinNullPointerException
        at rat.poison.game.WorldToScreenKt.worldToScreen(WorldToScreen.kt:14)
        at rat.poison.scripts.esp.IndicatorESPKt.w2sHandler(IndicatorESP.kt:121)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt:47)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt)
        at rat.poison.App.render(RatPoison.kt:217)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
kotlin.KotlinNullPointerException
        at rat.poison.game.WorldToScreenKt.worldToScreen(WorldToScreen.kt:14)
        at rat.poison.scripts.esp.IndicatorESPKt.w2sHandler(IndicatorESP.kt:121)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt:47)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt)
        at rat.poison.App.render(RatPoison.kt:217)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
kotlin.KotlinNullPointerException
        at rat.poison.game.WorldToScreenKt.worldToScreen(WorldToScreen.kt:14)
        at rat.poison.scripts.esp.IndicatorESPKt.w2sHandler(IndicatorESP.kt:121)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt:47)
        at rat.poison.scripts.esp.IndicatorESPKt$indicatorEsp$1.invoke(IndicatorESP.kt)
        at rat.poison.App.render(RatPoison.kt:217)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by AStupidRat** [comment]
Indicator esp has been a bit buggy, haven't had the chance to look into it yet. Id suggest just not using it for now.
