### ISSUE TITLE
Game crashes after awhile. I get the error below after i drag the sliders according to how i want it and whatnot.

### ISSUE THREAD

**Issue by codyxd** [AStupidRat/RatPoison#8]
waiting for CSGO
Initializing overlay
Exception in thread "Thread-9" javax.script.ScriptException: error: unresolved reference: KNIFE_T
KNIFE_T
^

        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:65)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:31)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
        at rat.poison.scripts.aim.SetAimKt$setAim$$inlined$every$1.invoke(Every.kt:26)
        at rat.poison.scripts.aim.SetAimKt$setAim$$inlined$every$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Waiting for CSGO
InterruptedException
java.lang.InterruptedException: sleep interrupted
        at java.lang.Thread.sleep(Native Method)
        at rat.poison.overlay.Overlay.getWindowHWND(Overlay.kt:217)
        at rat.poison.overlay.Overlay.monitorTargetApp(Overlay.kt:100)
        at rat.poison.overlay.Overlay.access$monitorTargetApp(Overlay.kt:17)
        at rat.poison.overlay.Overlay$start$1.invoke(Overlay.kt:66)
        at rat.poison.overlay.Overlay$start$1.invoke(Overlay.kt:17)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
OverlayWindowMonitorThread died!

**Comment by AStupidRat** [comment]
Is the 'it crashes after awhile' related to the error or is it a separate problem?

**Comment by codyxd** [comment]
I think its just that my lappy has become shit that its unable to handle the game. CSGO force closes and then that's what's written in the cmd.

**Comment by AStupidRat** [comment]
Just pushed a possible fix, lmk if it works and close this issue whenever.

**Comment by codyxd** [comment]
Well, as Ratpoison keeps getting updated, it seems to be fixing 
Thank you!
another issue i found out is that i think it still can't save to default config or the others. I mean, idk, the saving slow or something.
![Rat](https://user-images.githubusercontent.com/47775604/57178346-38dd1300-6e8c-11e9-9f14-3337912b76de.png)

This is the error thingy. Idk whether I got after saving or something but yeah, when i tried to save my settings, It wasn't able to save. So like, whenever i have to restart my csgo and open the cheat, i have to reconfigure it all.

**Comment by AStupidRat** [comment]
Saving works fine for me on the latest build, is it still broken for you?
